<?php echo $this->tag->getDoctype(); ?>
<!-- escreve o doctype que foi definido no ControllerBase -->
<html>
	<head>
		<?php echo $this->tag->getTitle(); ?>


		<!-- stylesheetLink ([array $parameters], [boolean $local]) -->
		<?php echo $this->tag->stylesheetLink("http://fonts.googleapis .com/css?family=Rosario", false);?>
		<?php echo $this->tag->stylesheetLink("css/styles.css"); ?>

		<!-- http://docs.phalconphp.com/en/latest/api/Phalcon_Tag.html -->

		<script type="text/javascript">

		//			aqui o objectivo era mostrar como se pode criar uma url com
		//          as convenções da framework, o ajax não está a funcionar

			$.ajax({
				url: "<?php echo $this->url->get("index/ajax") ?>"
			})
				.done(function() {
					alert("Done!");
				});

		</script>
	</head>
	<body>

		<h1>This is main action it will be shown for every controller or action executed within the application.</h1>
        <?php echo $this->getContent(); ?>


		<!-- javascriptInclude ([array $parameters], [boolean $local]) -->
		<?php echo $this->tag->javascriptInclude("http://ajax.googleapis .com/ajax/libs/jquery/1.7.1/jquery.min.js", false); ?>
		<?php echo $this->tag->javascriptInclude("javascript/jquery.js"); ?>
	</body>
</html>
