
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("noticia/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("noticia", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit noticia</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="lead">Lead</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lead", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="texto">Texto</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("texto", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="data">Data</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("data", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="titulo">Titulo</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("titulo", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="imagem">Imagem</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("imagem", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("Id_noticia"); ?></td>
        <td><?php echo $this->tag->submitButton("Save"); ?></td>
    </tr>
</table>

</form>
