
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("noticia/new", "Create noticia")) ?>
</div>

<?php echo $this->tag->form(array("noticia/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search noticia</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="Id_noticia">Id Of Noticia</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Id_noticia", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lead">Lead</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lead", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="texto">Texto</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("texto", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="data">Data</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("data", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="titulo">Titulo</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("titulo", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="imagem">Imagem</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("imagem", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
